version: "3.9"
volumes:
  volume1:
services:
    kafka1:
        image: 'bitnami/kafka:latest'
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
        volumes:
            - volume1:/bitnami/kafka
    ui:
        image: provectuslabs/kafka-ui:v0.7.1
        ports:
            - "8280:8080"
        environment:
            - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
            - KAFKA_CLUSTERS_0_NAME=kraft
    py:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: my_python_app
      working_dir: /app
      volumes:
        - ./:/app
      ports:
        - "5000:5000"
      environment:
        - KAFKA_HOST=host.docker.internal
        - KAFKA_PORT=9092

